language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get install -y clamav
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --check
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true