language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get install -y clamav
script:
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true