steps:
  - name: ':docker: Build'
    plugins:
      docker-compose#v2.4.1:
        build: app

  - wait

  - label: ':docker: Test Stable'
    command: .buildkite/build.sh
    plugins:
      docker-compose#v2.4.1:
        run: app

  - label: ':docker: Test Nightly'
    command: .buildkite/build-nightly.sh
    plugins:
      docker-compose#v2.4.1:
        run: app